### ISSUE TITLE
List of things to do before you add Antags (If you do)

### ISSUE THREAD

**Issue by VailTheWolf** [Citadel-Station-13/Citadel-Station-13-RP#1580]
Title says it all. Even though I don't want them on the server, I'm still willing to add input and compromise as it goes.

- Fix Antag spawns. No explanation needed. (Wizard and Ninja are confirmed broken.)

- Don't include kill objectives. This is the RP server. Shutting people out of the game because they were unlucky doesn't make people happy. Risk and reward type stuff is what main is for. Let's try to keep the RP server a safe haven for what it's named as.

- Changeling's evolution menu says "kill other changelings to get other evolution points." (Code revision needed for a different way to increase evolution.)

- TC values should be tweeked. For some reason they're in the 100s for prices. We can take off the extra 0. (Take away all the 0s instead maybe.)

- Nuke ops aka Mercenary game mode uplink implants and implanters do not currently work. (Try to test the ones at the Syndicate/ Mercenary base for confirmation.)

- Ground rules. Server rules aren't currently covering Antags in the RP tab last I checked. We need something set in stone. (If something is already there let me know and this point will be crossed out.)

- Thermal goggles in the Syndicate base currently don't work.

- Chameleon kits have issues with species sprites and most Teshari clothing sprites. (Most likely just a coding/pathing error.)

- Nuke Ops nuke does not spawn and does not correctly detonate (along with nuke codes not being generated). Even when admin spawned and bussed with fresh codes, the nuke only stuns players on every z-level for 10 seconds or so. No round end event is pathed.

- Technomancer abilities are unreliable and incorrectly pathed/aren't working at all. (Code review needed.)

- "Player xenomorphs don't seem to have sprites. I'd suggest looking at them all. Adding to that, the only xenomorph I could spawn is the larvae. There was another one without a sprite in the menu, but that's all I saw. From what the admin spawn menu is doing, I'm assuming they've been replaced with hostile vore mobs. When I didn't have a sprite I had to make a new mob to jump into just to change." (I've seen player controlled Xenos work during the "Passive Xeno" event. Update might have broken them since that point.)

- Only human and tajara mob types seem to be working for spawning mobs. (Possible Code review needed.)

- Death Commando doesn't have sprites for anything other than human, and fails to equip properly if you put equipment on them. (Sprite problems.)

- Space Ninja's deadman switch and grenade launcher don't seem to work. (Unknown issue.)

That's all I have right now. Good luck out there and be nice to each other please.
Edit: I've been adding things put in the comments. Also paying attention to #development-discussion-rp.
Edit 2: Updated again. Thank you Kersakof~

**Comment by Kersakof** [comment]
Specifically Wizard and Ninja spawns are in the phoron. I haven't tested anything else yet, but can if need be.

**Comment by AnalWerewolf** [comment]
> 
>     * Don't include kill objectives. This is the RP server. Shutting people out of the game because they were unlucky doesn't make people happy. Risk and reward type stuff is what main is for. Let's try to keep the RP server a safe haven for what it's named as.

Why not?
There is specifically an option for this already implemented where players can choose if they would like to allow antagonists to kill, capture, or vore their characters. There is even a special HUD, the antagHUD, that antagonists get which shows a correlating icon depending on what the player has chosen.

**Comment by Tename** [comment]
^ That sounds good but can someone verify it's working. I know a lot of the antag code is dated so we should make sure it works first.

**Comment by EldritchSigma** [comment]
First of all.. I cannot fathom why am I even bothering at this point.. Actually I do.. Had to do with Entropy I believe. 

The Antag HUD antags get are for vore specific events afaik, antags are unaffected because the vore code is so incredibly broken in regards to antags.  Just basicly mirroring what I said on discord with:

Also mirroring what I feel should be said about it:
I have absolutly no problem with antags.. if their objectives do not involve "Assassinate X, Occupation Y.".. worst, they can set that as their "ambition" from what I have heard. I only have one fucking character I enjoy playing and the rest is just once in a blue moon. I am heavily time constrained aswell, heck I bothered writing this up while I am waiting for my reactions to cool off. The time constrainment/time investment part I am sure I am not alone with.. I am very sure of that. Not everyone has the time to sit through a full round where you effectively cannot play your character cause "Assassinate is fun and engaging" and still have the nerves of being told "Lol just pway sOWOmethin else NYAAAA" by someone (no its not skylar or anyone really. Its just a generic jab). 

So yeah.. enjoy getting pulled into "**_<<'HRP'>_**> Assassinate plots" by some TG/Main regular who can play 3 rounds a day on fucking RP if they want so while some people can just do a fraction of that.  Heck maybe get maybe an hour at most in the evening. I sound very bitter and pissed, downright cynical. Why? Because its sickening that a weighted dice roll should decide if I get to play the game I used to like with a community that used to be good in a way I can enjoy it. Make assassinate either opt in or opt out, make sure its enforced proper and make sure the opt in/opt out system works. If I want to play TTT but on a fucking space station/research station I go on steam, download Gmod and just do that with a special map. That particular objective is the sole reason why powergaming is such a widespread issue. There are no respawns for your character you played. The rounds drag on for hours. You legitimately are locked out of your character. And suuure I have do have time writing a bloody complete crew record etc for a new character I just come up with. Cause of cause putting any more effort into records than this post is doable in like.. a couple hour. A couple hours most people do not really have nowadays. 

...Or you know.. go play TG because powergaming is fine there and its ttt but less balanced and more content...

**Comment by EldritchSigma** [comment]
First of all.. I cannot fathom why am I even bothering at this point.. Actually I do.. Had to do with Entropy I believe.

The Antag HUD antags get are for vore specific events afaik, antags are unaffected because the vore code is so incredibly broken in regards to antags. Just basicly mirroring what I said on discord with:

Also mirroring what I feel should be said about it:
I have absolutly no problem with antags.. if their objectives do not involve "Assassinate X, Occupation Y.".. worst, they can set that as their "ambition" from what I have heard. I only have one fucking character I enjoy playing and the rest is just once in a blue moon. I am heavily time constrained aswell, heck I bothered writing this up while I am waiting for something to cool off. The time constrainment/time investment part I am sure I am not alone with.. I am very sure of that. Not everyone has the time to sit through a full round where you effectively cannot play your character cause "Assassinate is fun and engaging" and still have the nerves of being told "Lol just pway sOWOmethin else NYAAAA" by someone (no its not skylar or anyone really. Its just a generic jab).

So yeah.. enjoy getting pulled into "<<'HRP'>> Assassinate plots" by some TG/Main regular who can play 3 rounds a day on fucking RP if they want so while some people can just do a fraction of that. Heck maybe get maybe an hour at most in the evening. I sound very bitter and pissed, downright cynical. Why? Because its sickening that a weighted dice roll should decide if I get to play the game I used to like with a community that used to be good in a way I can enjoy it. Make assassinate either opt in or opt out, make sure its enforced proper and make sure the opt in/opt out system works. If I want to play TTT but on a fucking space station/research station I go on steam, download Gmod and just do that with a special map. That particular objective is the sole reason why powergaming is such a widespread issue. There are no respawns for your character you played. The rounds drag on for hours. You legitimately are locked out of your character. And suuure I have do have time writing a bloody complete crew record etc for a new character I just come up with. Cause of cause putting any more effort into records than this post is doable in like.. a couple hour. A couple hours most people do not really have nowadays.

...Or you know.. go play TG because powergaming is fine there and its ttt but less balanced and more content...

**Comment by VailTheWolf** [comment]
Guys, this is a list. This isn't the place to debate the whys and hows. Add input in things that are broken and need fixing.

**Comment by lolman360** [comment]
nuke ops isn't a mode on rp afaik, mercenary is

so the "nuke op" "gamemode" bug isn't... actually a bug

the nuke explosion is though

**Comment by Tename** [comment]
Vail you should probably remove don't include kill objectives fomr the topic then because it is just creating a reason to debate those things.

**Comment by VailTheWolf** [comment]
Seeing as Black Major is putting a foot down and excluding Objectives entirety for this test, no, it is not being removed from the list. 
Don't comment on this issue for what you want removed from the list, only what younwant added.

**Comment by Kersakof** [comment]
Further examining the TC issue, everything is in 10s with super high powerful stuff being over 120. Etc instant kill things. There's also a shit ton of crates for some reason. I think it'd be easier to balance if we took the zeros off everything in the traitor uplink so we can properly balance things like TG's uplink. Otherwise we're gonna be dealing with 100 TC+

**Comment by Kersakof** [comment]
Changeling's evolution menu says "kill other changelings to get other evolution points." I'm not sure if we want to implement this if we aren't going for assassinate objectives.

**Comment by Kersakof** [comment]
Over half of technomancer's abilities don't work, and they get a shit ton more than a TG wizard.

**Comment by lolman360** [comment]
the amount of 0s behind tc just allows for more careful control of prices (5tc, 25tc items, etc would be rounded up or down to whole values with a tg-style uplink

it's more or less the same scenario when you compare our cargo system to tg's

**Comment by VailTheWolf** [comment]
Updated the list.

**Comment by Tename** [comment]
Kind of important one, binary keys need to be made was less accessible or rouge AI will not work.

**Comment by Tename** [comment]
#1598

**Comment by Tename** [comment]
** Fairly super important if we get antags. **
The bug with the bluespace harpoon being able to go anywhere if you have mesons needs to be fixed or the harpoon temp slashed out till it is. As it stands you can toss on mesas and go wherever with the harpoon.
