### ISSUE TITLE
Updated on join message broken

### ISSUE THREAD

**Issue by Tename** [Citadel-Station-13/Citadel-Station-13-RP#1602]
#### Brief description of the issue
It claims we were last updated on 

> Updated 8/18/2019

#### What you expected to happen
To say the date it was updated ont

#### What actually happened
not

#### Steps to reproduce
- join
- look at date updated message
- select ai
- phoron flood the station and get banned

#### Code Revision
- Server revision:  - 2019-11-09
46a33d11c27e129afb85b04750d6b61a997e5b0f 

 
#### Anything else you may wish to add:
- god i just really like ranch dressing on burgers, i mean even a1 is pretty good.

**Comment by KillianKirilenko** [comment]
My best guess is this is because the changelog itself hasn't been updated. [Changelogbot is running](https://github.com/Citadel-Station-13/Citadel-Station-13-RP/commits?author=CitadelStationBot), but it's not merging the changelogs it generates into the changelog html (possibly due to issues with the actual scripts or dependencies).

There's a problem with _this_ in that if the changelog merge script is run on the backlog in its current state, the changelog will all read the changes being done as on the same day, the day of the merger, rather than the day they were actually made.

**Comment by buffyuwu** [comment]
> My best guess is this is because the changelog itself hasn't been updated. [Changelogbot is running](https://github.com/Citadel-Station-13/Citadel-Station-13-RP/commits?author=CitadelStationBot), but it's not merging the changelogs it generates into the changelog html (possibly due to issues with the actual scripts or dependencies).
> 
> There's a problem with _this_ in that if the changelog merge script is run on the backlog in its current state, the changelog will all read the changes being done as on the same day, the day of the merger, rather than the day they were actually made.

i compiled the changelog with one of my recent PR's, maybe that will fix on sync

**Comment by buffyuwu** [comment]
update: still 8/18/2019 so ill look into it

**Comment by buffyuwu** [comment]
it’s some kind of MOTD type of thing set by an admin. nothing to do with changelogs
