### ISSUE TITLE
Teshari minor issue (Wheelchairs and More)

### ISSUE THREAD

**Issue by Saisni** [Citadel-Station-13/Citadel-Station-13-RP#2367]
#### Brief description of the bug
So, when you play a teshari, specifically the one with acquired amputation of both lower limbs, you get a certain ammount of issues, ranging from sprites, ending with specific abilities of teshari working...weird for such situation.

#### What you expected to happen
1)When you're on a wheelchair, you expect to be centered, to be actually inside the chair.
2)When you're on a wheelchair, yet alone without lower limbs, you'd expect to being... limited to the wheelchair range of motion.

#### What actually happened
1)The sprite seems to be "sitting" at the base of the chair, as in, it's overlayed directly on top of the wheelchair sprite. If you're short - you sit on the feet pad, if you're big... I didn't check what happens then.
Also character sprite goes over the wheelchair sprite when looked on the sides (as if you're not sitting in a chair, but standing by it).
Pixelshifting also only happens with the character sprite. I'm unsure if it can be made possible to pixelshift with a chair once buckled to it, but it would've been nice.

2)When you're using a wheelchair, your abilities keep on working. As in, teshari have an "Agility" ability, which makes them walk over tables, fall through railings, etc. Same works for the wheelchair, for some reason. I mean, its fascinatingly cool, looking how a teshari with acquired amputation casually hops on the bar counter in it's wheelchair, but something tells me it shouldn't work this way. And yes, I understand that it's just a toggle for an ability, but it's still a bit odd. 

#### Steps to reproduce
-1) Get a teshari character (with or without legs)
-2) Get them in a wheelchair
-3) Pretty much that's it. Sprites are wonky and ability still triggers. You might want to lose those legs to get full understanding how wicked it is to parkour around on a wheelchair.

#### Code Revision
BYOND Version: 513.1527
Server revision compiled on: 
Master commit: 233a2e3aa6176ba60f8c1818ba8a0b30acaa46ab 
Local commit: 0c67805ec71a93bb34320a2dfce94ce94e07b509
Server tools version: 4.5.3
 
#### Anything else you may wish to add:
Screenshots:
https://drive.google.com/file/d/15m08K2FBWap5B92jauvZ2loJ48UVpnp-/view?usp=sharing

**Comment by Greenjoe12345** [comment]
this overlay problem when going east or west is an issue at Polaris too
As is the fact wheelchair-bound teshari can go on tables and such, though it's glitchy-er for them there so that might be a separate issue in of itself

**Comment by buffyuwu** [comment]
I mean, people in wheelchairs have more range of motion than you think. An experienced person with a wheelchair can jump curbs, so why not a counter? 

Sprite issues relating to amputation mechanics are... Difficult, to understate it. I wouldn't expect this part of the issue to be resolved anytime soon, due to the lack of spriters/active developers for this branch.

Not only that, but it is up to **you** as the author of the disabled character, to both determine and write the level of disability your character has, not us as developers. Some characters may write cool gadgets that allow them to more easily interact with the world, and others may just be interested in the accessibility of climbing tables and counters. Not only that, but I nor anyone else is interested in rewriting table/bits of combat code to accommodate this interpretation of realism, you know?

Thank you for bringing this up!!
